//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class agentMembershipCash
    {
        public long agentMembershipCashId { get; set; }
        public Nullable<long> subscriptionFeesId { get; set; }
        public Nullable<long> cashTransId { get; set; }
        public Nullable<long> membershipId { get; set; }
        public Nullable<long> agentId { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<long> updateUserId { get; set; }
        public byte isActive { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<long> createUserId { get; set; }
        public string notes { get; set; }
        public string subscriptionType { get; set; }
        public Nullable<int> monthsCount { get; set; }
        public decimal discountValue { get; set; }
        public decimal total { get; set; }
    
        public virtual agents agents { get; set; }
        public virtual cashTransfer cashTransfer { get; set; }
        public virtual memberships memberships { get; set; }
        public virtual subscriptionFees subscriptionFees { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
