//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class cities
    {
        public long cityId { get; set; }
        public string cityCode { get; set; }
        public Nullable<long> countryId { get; set; }
    
        public virtual countriesCodes countriesCodes { get; set; }
    }
}
