//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class couponsInvoices
    {
        public long id { get; set; }
        public Nullable<long> couponId { get; set; }
        public Nullable<long> InvoiceId { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<long> createUserId { get; set; }
        public Nullable<long> updateUserId { get; set; }
        public decimal discountValue { get; set; }
        public byte discountType { get; set; }
        public string forAgents { get; set; }
    
        public virtual coupons coupons { get; set; }
        public virtual invoices invoices { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
