//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class groupObject
    {
        public long id { get; set; }
        public Nullable<long> groupId { get; set; }
        public Nullable<long> objectId { get; set; }
        public string notes { get; set; }
        public byte addOb { get; set; }
        public byte updateOb { get; set; }
        public byte deleteOb { get; set; }
        public byte showOb { get; set; }
        public byte reportOb { get; set; }
        public byte levelOb { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<long> createUserId { get; set; }
        public Nullable<long> updateUserId { get; set; }
        public int isActive { get; set; }
    
        public virtual groups groups { get; set; }
        public virtual objects objects { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
