//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoiceOrder
    {
        public long id { get; set; }
        public Nullable<long> invoiceId { get; set; }
        public Nullable<long> orderId { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<long> itemsTransferId { get; set; }
    
        public virtual invoices invoices { get; set; }
        public virtual invoices invoices1 { get; set; }
        public virtual itemsTransfer itemsTransfer { get; set; }
    }
}
