//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoiceClassDiscount
    {
        public long invClassDiscountId { get; set; }
        public Nullable<long> invClassId { get; set; }
        public Nullable<long> invoiceId { get; set; }
        public decimal discountValue { get; set; }
        public byte discountType { get; set; }
    
        public virtual invoices invoices { get; set; }
        public virtual invoicesClass invoicesClass { get; set; }
    }
}
