//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemsTransferIngredients
    {
        public long itemsTransIngredId { get; set; }
        public Nullable<long> itemsTransId { get; set; }
        public Nullable<long> dishIngredId { get; set; }
        public byte isActive { get; set; }
        public string notes { get; set; }
    
        public virtual dishIngredients dishIngredients { get; set; }
        public virtual itemsTransfer itemsTransfer { get; set; }
    }
}
