//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemOrderPreparing
    {
        public long itemOrderId { get; set; }
        public Nullable<long> itemUnitId { get; set; }
        public Nullable<long> orderPreparingId { get; set; }
        public Nullable<int> quantity { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<long> createUserId { get; set; }
        public Nullable<long> updateUserId { get; set; }
        public Nullable<long> itemsTransId { get; set; }
    
        public virtual itemsTransfer itemsTransfer { get; set; }
        public virtual itemsUnits itemsUnits { get; set; }
        public virtual orderPreparing orderPreparing { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
