//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public items()
        {
            this.itemsExtra = new HashSet<itemsExtra>();
            this.itemsExtra1 = new HashSet<itemsExtra>();
            this.itemsMaterials = new HashSet<itemsMaterials>();
            this.itemsMaterials1 = new HashSet<itemsMaterials>();
            this.itemsProp = new HashSet<itemsProp>();
            this.itemsUnits = new HashSet<itemsUnits>();
            this.serials = new HashSet<serials>();
        }
    
        public long itemId { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string details { get; set; }
        public string type { get; set; }
        public string image { get; set; }
        public decimal taxes { get; set; }
        public byte isActive { get; set; }
        public int min { get; set; }
        public int max { get; set; }
        public Nullable<long> categoryId { get; set; }
        public Nullable<long> parentId { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<long> createUserId { get; set; }
        public Nullable<long> updateUserId { get; set; }
        public Nullable<long> minUnitId { get; set; }
        public Nullable<long> maxUnitId { get; set; }
        public decimal avgPurchasePrice { get; set; }
        public Nullable<long> tagId { get; set; }
        public string notes { get; set; }
        public string categoryString { get; set; }
        public bool isExpired { get; set; }
        public int alertDays { get; set; }
    
        public virtual categories categories { get; set; }
        public virtual tags tags { get; set; }
        public virtual units units { get; set; }
        public virtual units units1 { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        public virtual users users2 { get; set; }
        public virtual users users3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itemsExtra> itemsExtra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itemsExtra> itemsExtra1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itemsMaterials> itemsMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itemsMaterials> itemsMaterials1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itemsProp> itemsProp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itemsUnits> itemsUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<serials> serials { get; set; }
    }
}
