//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemsTransfer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public itemsTransfer()
        {
            this.invoiceOrder = new HashSet<invoiceOrder>();
            this.itemOrderPreparing = new HashSet<itemOrderPreparing>();
            this.itemsTransfer1 = new HashSet<itemsTransfer>();
            this.itemsTransferIngredients = new HashSet<itemsTransferIngredients>();
            this.itemTransferOffer = new HashSet<itemTransferOffer>();
        }
    
        public long itemsTransId { get; set; }
        public long quantity { get; set; }
        public Nullable<long> invoiceId { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<long> createUserId { get; set; }
        public Nullable<long> updateUserId { get; set; }
        public string notes { get; set; }
        public decimal price { get; set; }
        public Nullable<long> itemUnitId { get; set; }
        public string itemSerial { get; set; }
        public Nullable<long> inventoryItemLocId { get; set; }
        public Nullable<long> offerId { get; set; }
        public decimal profit { get; set; }
        public decimal purchasePrice { get; set; }
        public string cause { get; set; }
        public Nullable<decimal> itemTax { get; set; }
        public Nullable<decimal> itemUnitPrice { get; set; }
        public Nullable<decimal> offerValue { get; set; }
        public Nullable<decimal> offerType { get; set; }
        public string forAgents { get; set; }
        public Nullable<long> mainCourseId { get; set; }
    
        public virtual inventoryItemLocation inventoryItemLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoiceOrder> invoiceOrder { get; set; }
        public virtual invoices invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itemOrderPreparing> itemOrderPreparing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itemsTransfer> itemsTransfer1 { get; set; }
        public virtual itemsTransfer itemsTransfer2 { get; set; }
        public virtual itemsUnits itemsUnits { get; set; }
        public virtual offers offers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itemsTransferIngredients> itemsTransferIngredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itemTransferOffer> itemTransferOffer { get; set; }
    }
}
