//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class menuSettings
    {
        public long menuSettingId { get; set; }
        public long itemUnitId { get; set; }
        public bool sat { get; set; }
        public bool sun { get; set; }
        public bool mon { get; set; }
        public bool tues { get; set; }
        public bool wed { get; set; }
        public bool thur { get; set; }
        public bool fri { get; set; }
        public Nullable<decimal> preparingTime { get; set; }
        public byte isActive { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<long> updateUserId { get; set; }
        public Nullable<long> createUserId { get; set; }
        public Nullable<long> branchId { get; set; }
    
        public virtual branches branches { get; set; }
        public virtual itemsUnits itemsUnits { get; set; }
        public virtual users users { get; set; }
    }
}
