//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class posSetting
    {
        public long posSettingId { get; set; }
        public Nullable<long> posId { get; set; }
        public Nullable<long> saleInvPrinterId { get; set; }
        public Nullable<long> reportPrinterId { get; set; }
        public Nullable<long> kitchenPrinterId { get; set; }
        public Nullable<long> saleInvPapersizeId { get; set; }
        public Nullable<long> kitchenPapersizeId { get; set; }
        public string posSerial { get; set; }
        public Nullable<long> docPapersizeId { get; set; }
        public string posDeviceCode { get; set; }
        public Nullable<long> posSerialId { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<long> createUserId { get; set; }
        public Nullable<long> updateUserId { get; set; }
    
        public virtual paperSize paperSize { get; set; }
        public virtual paperSize paperSize1 { get; set; }
        public virtual pos pos { get; set; }
        public virtual posSerials posSerials { get; set; }
        public virtual printers printers { get; set; }
        public virtual printers printers1 { get; set; }
        public virtual printers printers2 { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
