//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramDetails
    {
        public long id { get; set; }
        public string programName { get; set; }
        public int branchCount { get; set; }
        public int posCount { get; set; }
        public int userCount { get; set; }
        public int vendorCount { get; set; }
        public int customerCount { get; set; }
        public int itemCount { get; set; }
        public int saleinvCount { get; set; }
        public Nullable<int> programIncId { get; set; }
        public Nullable<int> versionIncId { get; set; }
        public string versionName { get; set; }
        public int storeCount { get; set; }
        public string packageSaleCode { get; set; }
        public string customerServerCode { get; set; }
        public Nullable<System.DateTime> expireDate { get; set; }
        public Nullable<bool> isOnlineServer { get; set; }
        public string packageNumber { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<bool> isLimitDate { get; set; }
        public Nullable<bool> isLimitCount { get; set; }
        public bool isActive { get; set; }
        public string packageName { get; set; }
        public Nullable<System.DateTime> bookDate { get; set; }
        public Nullable<int> pId { get; set; }
        public Nullable<int> pcdId { get; set; }
        public string customerName { get; set; }
        public string customerLastName { get; set; }
        public string agentName { get; set; }
        public string agentLastName { get; set; }
        public string agentAccountName { get; set; }
        public bool isServerActivated { get; set; }
        public Nullable<System.DateTime> activatedate { get; set; }
        public Nullable<System.DateTime> pocrDate { get; set; }
        public Nullable<int> poId { get; set; }
        public string upnum { get; set; }
        public string notes { get; set; }
        public string isDemo { get; set; }
    }
}
