//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class setValues
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public setValues()
        {
            this.userSetValues = new HashSet<userSetValues>();
        }
    
        public long valId { get; set; }
        public string value { get; set; }
        public int isDefault { get; set; }
        public int isSystem { get; set; }
        public string notes { get; set; }
        public Nullable<long> settingId { get; set; }
    
        public virtual setting setting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userSetValues> userSetValues { get; set; }
    }
}
