<Project>
  <PropertyGroup>
    <BeforePack>GenerateNupkgProps;$(BeforePack)</BeforePack>
    <PropsFilePath>$(BaseIntermediateOutputPath)$(PackageId).props</PropsFilePath>
  </PropertyGroup>
  <ItemGroup>
    <None Include="$(PropsFilePath)" PackagePath="build" Pack="true" />
  </ItemGroup>
  <Target Name="GenerateNupkgProps" Inputs="$(MSBuildThisFileFullPath)" Outputs="$(PropsFilePath)">
    <PropertyGroup>
      <PropsFileContents
        >
<Project>
  <ItemGroup>
    <DotNetCliToolReference Include="$(PackageId)" Version="$(PackageVersion)" />
  </ItemGroup>
  <PropertyGroup>
    <SgenPackSerializer Condition="'%24(SgenPackSerializer)'==''">True</SgenPackSerializer>
  </PropertyGroup>
  <ItemGroup Condition="'%24(SgenPackSerializer)'=='True'">
    <BuildOutputInPackage Include="%24(OutputPath)%24(AssemblyName).XmlSerializers.dll" />
  </ItemGroup>
</Project>
      </PropsFileContents
      >
    </PropertyGroup>
    <WriteLinesToFile File="$(PropsFilePath)" Lines="$(PropsFileContents)" Overwrite="true" />
  </Target>
</Project>
